site_name: Peppy
nav:
  - Home: README.md
  - Introduction: intro.md
  - Installing and Hello World: hello-world.md
  - How-to Guides:
    - How to use peppy: jupyter_build/tutorial.md
    - How to use sample subannotation: jupyter_build/subannotation.md
    - Subprojects tutorial: jupyter_build/subprojects.md
  - Reference:
    - Advanced: advanced.md
    - Cluster computing: cluster-computing.md
    - Configuration files: config-files.md
    - Contributing: contributing.md
    - Derived columns: derived-columns.md
    - Implied columns: implied-columns.md
    - Models: models.md
    - Pipeline interface: pipeline-interface.md
    - Project configuration: project-config.md
    - Sample annotation sheet: sample-annotation-sheet.md
  #- API: autodoc_build/peppy_oradoc.md
  - API: autodoc_build/peppy.md
  #- API: autodoc_build/peppy_pydoc.md
  #  - Project: autodoc_build/project.md
  #  - Sample: autodoc_build/sample.md
  #  - Tools: autodoc_build/utils.md
  - FAQ: faq.md
  - Support: support.md
  - Changelog: changelog.md

theme: databio

plugins:
  - databio:
      autodoc_build: "docs/autodoc_build"
      autodoc_package: "peppy"
      no_top_level: true
  - search



#markdown_extensions:
#  - markdown_include.include:
#    base_path: docs

theme: databio

plugins:
  - databio:
      autodoc_build: "docs/autodoc_build"
      autodoc_package: "peppy"
      no_top_level: true
  - search
