metadata:
  output_dir: ${PROCESSED}/microtest
  results_subdir: results_pipeline
  submission_subdir: submission
  pipelines_dir: ${CODE}/pipelines
  sample_annotation: microtest_sample_annotation.csv
  merge_table: microtest_merge_table.csv

derived_attributes: [data_source]

data_sources:
  bsf_samples: "{RAWDATA}{flowcell}/{flowcell}_{lane}_samples/{flowcell}_{lane}#{BSF_name}.bam"
  microtest: "${RESOURCES}/microtest/{sample_name}.bam"
  microtest_merge: "${RESOURCES}/microtest/{sample_name}{file_number}.bam"

subprojects:
  config_test:
    pipeline_config:
      wgbs.py: wgbs_ds.yaml

implied_attributes:
  organism:
    human:
      genomes: hg19
      transcriptome: hg19_cdna
    mouse:
      genome: mm10
      transcriptome: mm10_cdna

pipeline_config:
  rrbs.py: rrbs_config.yaml

pipeline_args:
  rnaBitSeq.py:
    "-w": 50
