site_name: Peppy
nav:
  - Introduction: README.md
    
  - How-to Guides:
    - How to use peppy: jupyter_build/tutorial.md
    - How to use sample subannotation: jupyter_build/subannotation.md
    - Subprojects tutorial: jupyter_build/subprojects.md

  - Reference:
    - Advanced: advanced.md
    - Cluster computing: cluster-computing.md
    - Configuration files: config-files.md
    - Contributing: contributing.md
    - Derived columns: derived-columns.md
    - FAQ: faq.md
    - Features: features.md
    - Hello World: hello-world.md
    - Implied columns: implied-columns.md
    - Introduction: intro.md
    - Models: models.md
    - Pipeline interface: pipeline-interface.md
    - Project configuration: project-config.md
    - Sample annotation sheet: sample-annotation-sheet.md

  - API: autodoc_build/peppy.md
  - Changelog: changelog.md
  - Support: support.md
  - Tutorials: tutorials.md

#markdown_extensions:
#  - markdown_include.include:
#    base_path: docs

#theme: readthedocs
