testpipeline.sh:
  name: test_pipeline
  looper_args: False
  arguments:
    "--input": file
  resources:
    default:
      file_size: "0"
      cores: "8"
      mem: "32000"
      time: "2-00:00:00"
      partition: "longq"